---
title: "CascoBay spatial"
output: html_document
date: '2022-04-25'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages({
  library(cascophys)
  library(fvcom)
  library(sf)
  library(dplyr)
  library(ncdf4)
  library(leaflet)
})

# Estimate the bounding box of a projected bounding box
# adapted from 
# https://stackoverflow.com/questions/55050684/transform-result-of-st-bbox-to-other-crs
# @param x st_bbox
# @param n sample the extent into a grid with this many x,y divisions
# @param crs the desired output CRS
transform_bb <- function(x, n = 10, crs = 4326){
  x |>
    sf::st_make_grid(n=n) |>
    sf::st_transform(crs = crs) |>
    sf::st_bbox()
}
```



```{r}
CB <- cascophys::CascoBayPhysics()
```

```{r}
x <- read_deployment()
xy <- ll2xy(x)
```



```{r, echo = FALSE}
leaflet() |>
  addTiles() |>
  addPolygons(data = sf::st_convex_hull(CB$M) |> sf::st_transform(4326),  
              fill = FALSE, color = "purple", weight = 1)
```

